### ISSUE TITLE
Generate unique names for cluster managers

### ISSUE THREAD

**Issue by rvansa** [vert-x3/vertx-infinispan#55] opened 2018-08-10 14:30 UTC
I am trying to run several clustered Vertx instances in single VM (during testing). I had to allow duplicate domains for JMX, but even with that ~~the startup fails with~~ an error appears in the log
```
14:46:59,136 INFO  (vert.x-worker-thread-0) [o.i.j.JmxUtil] ISPN000138: Could not register object with name: org.infinispan:type=CacheManager,name="DefaultCacheManager",component=GlobalXSiteAdminOperations javax.management.InstanceAlreadyExistsException: org.infinispan:type=CacheManager,name="DefaultCacheManager",component=GlobalXSiteAdminOperations
    at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
    at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
    at org.infinispan.jmx.SecurityActions.lambda$registerMBean$0(SecurityActions.java:42)
    at org.infinispan.security.Security.doPrivileged(Security.java:89)
    at org.infinispan.jmx.SecurityActions.doPrivileged(SecurityActions.java:33)
```

To make clustering work out-of-box we need to make sure that the cache managers are named differently.

**Comment by karesti** [comment] 2018-08-13 11:03
For your tests today, you can pass yourself the cacheManager. Allowing duplicate domain names is the default value in the 3.5.x cluster manager, so you don't need to provide any infinispan.xml if you don't need to change any other value.

```java
public void useExistingCacheManager(DefaultCacheManager cacheManager) {
    ClusterManager mgr = new InfinispanClusterManager(cacheManager);

    VertxOptions options = new VertxOptions().setClusterManager(mgr);

    Vertx.clusteredVertx(options, res -> {
      if (res.succeeded()) {
        Vertx vertx = res.result();
      } else {
        // failed!
      }
    });
  }
```

For the 3.6.x version that is not yet released, we will either fix this usability testing problem in the cluster manager or in infinispan

**Comment by tsegismont** [comment] 2018-09-24 13:00
@rvansa sorry for the late reply.

Vert.x 3.6 will use a version of Infinispan which has the fix for [ISPN-8395](https://issues.jboss.org/browse/ISPN-8395). That is, 9.2.0.Final or later.

Closing this one since the problem is fixed in master already.

**Closed by tsegismont** 2018-09-24 13:00 UTC
